name: bigscience/bloom-560m
class_name: BloomForCausalLM
tokenizer_class: BloomTokenizerFast
tokenizer_name: bigscience/bloom-560m
inner_params:
- transformer.h.20.mlp.dense_h_to_4h.weight
- transformer.h.20.mlp.dense_4h_to_h.weight
- transformer.h.21.mlp.dense_h_to_4h.weight
- transformer.h.21.mlp.dense_4h_to_h.weight
- transformer.h.22.mlp.dense_h_to_4h.weight
- transformer.h.22.mlp.dense_4h_to_h.weight
- transformer.h.23.mlp.dense_h_to_4h.weight
- transformer.h.23.mlp.dense_4h_to_h.weight