name: bigscience/bloom-560m
class_name: BloomForSequenceClassification
tokenizer_class: BloomTokenizerFast
tokenizer_name: bigscience/bloom-560m
inner_params:
- transformer.h.0.self_attention.query_key_value.weight
- transformer.h.0.self_attention.dense.weight
- transformer.h.0.mlp.dense_h_to_4h.weight
- transformer.h.0.mlp.dense_4h_to_h.weight
- transformer.h.1.self_attention.query_key_value.weight
- transformer.h.1.self_attention.dense.weight
- transformer.h.1.mlp.dense_h_to_4h.weight
- transformer.h.1.mlp.dense_4h_to_h.weight
- transformer.h.2.self_attention.query_key_value.weight
- transformer.h.2.self_attention.dense.weight
- transformer.h.2.mlp.dense_h_to_4h.weight
- transformer.h.2.mlp.dense_4h_to_h.weight
- transformer.h.3.self_attention.query_key_value.weight
- transformer.h.3.self_attention.dense.weight
- transformer.h.3.mlp.dense_h_to_4h.weight
- transformer.h.3.mlp.dense_4h_to_h.weight
- transformer.h.4.self_attention.query_key_value.weight
- transformer.h.4.self_attention.dense.weight
- transformer.h.4.mlp.dense_h_to_4h.weight
- transformer.h.4.mlp.dense_4h_to_h.weight
- transformer.h.5.self_attention.query_key_value.weight
- transformer.h.5.self_attention.dense.weight
- transformer.h.5.mlp.dense_h_to_4h.weight
- transformer.h.5.mlp.dense_4h_to_h.weight
- transformer.h.6.self_attention.query_key_value.weight
- transformer.h.6.self_attention.dense.weight
- transformer.h.6.mlp.dense_h_to_4h.weight
- transformer.h.6.mlp.dense_4h_to_h.weight
- transformer.h.7.self_attention.query_key_value.weight
- transformer.h.7.self_attention.dense.weight
- transformer.h.7.mlp.dense_h_to_4h.weight
- transformer.h.7.mlp.dense_4h_to_h.weight
- transformer.h.8.self_attention.query_key_value.weight
- transformer.h.8.self_attention.dense.weight
- transformer.h.8.mlp.dense_h_to_4h.weight
- transformer.h.8.mlp.dense_4h_to_h.weight
- transformer.h.9.self_attention.query_key_value.weight
- transformer.h.9.self_attention.dense.weight
- transformer.h.9.mlp.dense_h_to_4h.weight
- transformer.h.9.mlp.dense_4h_to_h.weight
- transformer.h.10.self_attention.query_key_value.weight
- transformer.h.10.self_attention.dense.weight
- transformer.h.10.mlp.dense_h_to_4h.weight
- transformer.h.10.mlp.dense_4h_to_h.weight
- transformer.h.11.self_attention.query_key_value.weight
- transformer.h.11.self_attention.dense.weight
- transformer.h.11.mlp.dense_h_to_4h.weight
- transformer.h.11.mlp.dense_4h_to_h.weight
- transformer.h.12.self_attention.query_key_value.weight
- transformer.h.12.self_attention.dense.weight
- transformer.h.12.mlp.dense_h_to_4h.weight
- transformer.h.12.mlp.dense_4h_to_h.weight
- transformer.h.13.self_attention.query_key_value.weight
- transformer.h.13.self_attention.dense.weight
- transformer.h.13.mlp.dense_h_to_4h.weight
- transformer.h.13.mlp.dense_4h_to_h.weight
- transformer.h.14.self_attention.query_key_value.weight
- transformer.h.14.self_attention.dense.weight
- transformer.h.14.mlp.dense_h_to_4h.weight
- transformer.h.14.mlp.dense_4h_to_h.weight
- transformer.h.15.self_attention.query_key_value.weight
- transformer.h.15.self_attention.dense.weight
- transformer.h.15.mlp.dense_h_to_4h.weight
- transformer.h.15.mlp.dense_4h_to_h.weight
- transformer.h.16.self_attention.query_key_value.weight
- transformer.h.16.self_attention.dense.weight
- transformer.h.16.mlp.dense_h_to_4h.weight
- transformer.h.16.mlp.dense_4h_to_h.weight
- transformer.h.17.self_attention.query_key_value.weight
- transformer.h.17.self_attention.dense.weight
- transformer.h.17.mlp.dense_h_to_4h.weight
- transformer.h.17.mlp.dense_4h_to_h.weight
- transformer.h.18.self_attention.query_key_value.weight
- transformer.h.18.self_attention.dense.weight
- transformer.h.18.mlp.dense_h_to_4h.weight
- transformer.h.18.mlp.dense_4h_to_h.weight
- transformer.h.19.self_attention.query_key_value.weight
- transformer.h.19.self_attention.dense.weight
- transformer.h.19.mlp.dense_h_to_4h.weight
- transformer.h.19.mlp.dense_4h_to_h.weight
- transformer.h.20.self_attention.query_key_value.weight
- transformer.h.20.self_attention.dense.weight
- transformer.h.20.mlp.dense_h_to_4h.weight
- transformer.h.20.mlp.dense_4h_to_h.weight
- transformer.h.21.self_attention.query_key_value.weight
- transformer.h.21.self_attention.dense.weight
- transformer.h.21.mlp.dense_h_to_4h.weight
- transformer.h.21.mlp.dense_4h_to_h.weight
- transformer.h.22.self_attention.query_key_value.weight
- transformer.h.22.self_attention.dense.weight
- transformer.h.22.mlp.dense_h_to_4h.weight
- transformer.h.22.mlp.dense_4h_to_h.weight
- transformer.h.23.self_attention.query_key_value.weight
- transformer.h.23.self_attention.dense.weight
- transformer.h.23.mlp.dense_h_to_4h.weight
- transformer.h.23.mlp.dense_4h_to_h.weight

pt: /home/anonymous-xme/bloom-finetune/results/bloom-560m/finetuning-fever-1L-lr15-wt13-malayalam-pred/checkpoint-6562/pytorch_model.bin