name: bigscience/bloom-560m
class_name: BloomForSequenceClassification
tokenizer_class: BloomTokenizerFast
tokenizer_name: bigscience/bloom-560m
inner_params:
- transformer.h.4.mlp.dense_h_to_4h.weight
- transformer.h.4.mlp.dense_4h_to_h.weight
- transformer.h.5.mlp.dense_h_to_4h.weight
- transformer.h.5.mlp.dense_4h_to_h.weight
- transformer.h.6.mlp.dense_h_to_4h.weight
- transformer.h.6.mlp.dense_4h_to_h.weight
- transformer.h.7.mlp.dense_h_to_4h.weight
- transformer.h.7.mlp.dense_4h_to_h.weight

pt: ${hydra:runtime.cwd}/data/fever/bloom_models/bloom-560m-1L-french-13124iter.bin