name: bert-base-multilingual-uncased
class_name: AutoModelForSequenceClassification
tokenizer_class: AutoTokenizer
tokenizer_name: bert-base-multilingual-uncased
inner_params:
- bert.encoder.layer.0.intermediate.dense.weight
- bert.encoder.layer.0.output.dense.weight
- bert.encoder.layer.1.intermediate.dense.weight
- bert.encoder.layer.1.output.dense.weight
- bert.encoder.layer.2.intermediate.dense.weight
- bert.encoder.layer.2.output.dense.weight
- bert.encoder.layer.3.intermediate.dense.weight
- bert.encoder.layer.3.output.dense.weight

pt: ${hydra:runtime.cwd}/data/fever/mbert_models/mbert-uncased-spanish-6562iter.bin