name: bert-base-multilingual-uncased
class_name: AutoModelForSequenceClassification
tokenizer_class: AutoTokenizer
tokenizer_name: bert-base-multilingual-uncased
inner_params:
- bert.encoder.layer.8.intermediate.dense.weight
- bert.encoder.layer.8.output.dense.weight
- bert.encoder.layer.9.intermediate.dense.weight
- bert.encoder.layer.9.output.dense.weight
- bert.encoder.layer.10.intermediate.dense.weight
- bert.encoder.layer.10.output.dense.weight
- bert.encoder.layer.11.intermediate.dense.weight
- bert.encoder.layer.11.output.dense.weight


pt:  /home/anonymous-xme/bloom-finetune/results/mbert-uncased/finetuning-fever-1L-kannada-lr15-wt13-pred/checkpoint-9843/pytorch_model.bin
