name: bert-base-multilingual-uncased
class_name: AutoModelForSequenceClassification
tokenizer_class: AutoTokenizer
tokenizer_name: bert-base-multilingual-uncased
inner_params:
- bert.encoder.layer.0.intermediate.dense.weight
- bert.encoder.layer.0.output.dense.weight
- bert.encoder.layer.1.intermediate.dense.weight
- bert.encoder.layer.1.output.dense.weight
- bert.encoder.layer.2.intermediate.dense.weight
- bert.encoder.layer.2.output.dense.weight
- bert.encoder.layer.3.intermediate.dense.weight
- bert.encoder.layer.3.output.dense.weight
- bert.encoder.layer.4.intermediate.dense.weight
- bert.encoder.layer.4.output.dense.weight
- bert.encoder.layer.5.intermediate.dense.weight
- bert.encoder.layer.5.output.dense.weight
- bert.encoder.layer.6.intermediate.dense.weight
- bert.encoder.layer.6.output.dense.weight
- bert.encoder.layer.7.intermediate.dense.weight
- bert.encoder.layer.7.output.dense.weight
- bert.encoder.layer.8.intermediate.dense.weight
- bert.encoder.layer.8.output.dense.weight
- bert.encoder.layer.9.intermediate.dense.weight
- bert.encoder.layer.9.output.dense.weight
- bert.encoder.layer.10.intermediate.dense.weight
- bert.encoder.layer.10.output.dense.weight
- bert.encoder.layer.11.intermediate.dense.weight
- bert.encoder.layer.11.output.dense.weight

pt: ${hydra:runtime.cwd}/data/fever/mbert_models/mbert-english-19686iter.bin