name: xlm-roberta-base
class_name: AutoModelForSequenceClassification
tokenizer_class: AutoTokenizer
tokenizer_name: xlm-roberta-base
inner_params:
- roberta.encoder.layer.0.intermediate.dense.weight
- roberta.encoder.layer.0.output.dense.weight
- roberta.encoder.layer.1.intermediate.dense.weight
- roberta.encoder.layer.1.output.dense.weight
- roberta.encoder.layer.2.intermediate.dense.weight
- roberta.encoder.layer.2.output.dense.weight
- roberta.encoder.layer.3.intermediate.dense.weight
- roberta.encoder.layer.3.output.dense.weight
- roberta.encoder.layer.4.intermediate.dense.weight
- roberta.encoder.layer.4.output.dense.weight
- roberta.encoder.layer.5.intermediate.dense.weight
- roberta.encoder.layer.5.output.dense.weight
- roberta.encoder.layer.6.intermediate.dense.weight
- roberta.encoder.layer.6.output.dense.weight
- roberta.encoder.layer.7.intermediate.dense.weight
- roberta.encoder.layer.7.output.dense.weight
- roberta.encoder.layer.8.intermediate.dense.weight
- roberta.encoder.layer.8.output.dense.weight
- roberta.encoder.layer.9.intermediate.dense.weight
- roberta.encoder.layer.9.output.dense.weight
- roberta.encoder.layer.10.intermediate.dense.weight
- roberta.encoder.layer.10.output.dense.weight
- roberta.encoder.layer.11.intermediate.dense.weight
- roberta.encoder.layer.11.output.dense.weight

pt: ${hydra:runtime.cwd}/data/fever/xlm_model/xlm-roberta-mixed-28953iter.bin