name: xlm-roberta-base
class_name: AutoModelForSequenceClassification
tokenizer_class: AutoTokenizer
tokenizer_name: xlm-roberta-base
inner_params:
- roberta.encoder.layer.2.intermediate.dense.weight
- roberta.encoder.layer.2.output.dense.weight
- roberta.encoder.layer.4.intermediate.dense.weight
- roberta.encoder.layer.4.output.dense.weight
- roberta.encoder.layer.6.intermediate.dense.weight
- roberta.encoder.layer.6.output.dense.weight
- roberta.encoder.layer.9.intermediate.dense.weight
- roberta.encoder.layer.9.output.dense.weight

pt: ${hydra:runtime.cwd}/data/fever/xlm_model/xlm-roberta-french-32810iter.bin