name: xlm-roberta-base
class_name: AutoModelForSequenceClassification
tokenizer_class: AutoTokenizer
tokenizer_name: xlm-roberta-base
inner_params:
- roberta.encoder.layer.0.intermediate.dense.weight
- roberta.encoder.layer.0.output.dense.weight
- roberta.encoder.layer.1.intermediate.dense.weight
- roberta.encoder.layer.1.output.dense.weight
- roberta.encoder.layer.2.intermediate.dense.weight
- roberta.encoder.layer.2.output.dense.weight
- roberta.encoder.layer.3.intermediate.dense.weight
- roberta.encoder.layer.3.output.dense.weight

# pt: ${hydra:runtime.cwd}/data/fever/xlm_model/xlm-roberta-english-29529iter.bin